import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import Link from "next/link";
import { ChartColumnBigIcon } from "lucide-react";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
} from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import UserDropdown from "./user-dropdown";
import { Toaster } from "@/components/ui/toaster";

const poppins = Poppins({
 weight: ['400', '600'],
 subsets: ['latin'],
 display: 'swap',
 variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Social dept finances",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.variable} bg-white  antialiased`}>
          <nav className="bg-primary p-4 text-white h-20 flex items-center justify-between">
            <Link
              href="/"
              className="font-bold text-2xl flex gap-1 items-center"
            >
              <ChartColumnBigIcon className="text-lime-500" /> Social dept finances
            </Link>
            <div>
              <SignedOut>
                <div className="flex items-center">
                  <Button asChild variant="link" className="text-white">
                    <SignInButton />
                  </Button>
                  <Button asChild variant="link" className="text-white">
                    <SignUpButton />
                  </Button>
                </div>
              </SignedOut>
              <SignedIn>
                <UserDropdown />
              </SignedIn>
            </div>
          </nav>
          {children}
          <Toaster/>
        </body>
      </html>
    </ClerkProvider>
  );
}